//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.21 at 10:08:23 AM EDT 
//


package org.nanocontext.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstructorArgType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConstructorArgType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://nanocontext.org/v1/schema/ctx}bean"/&gt;
 *         &lt;element ref="{http://nanocontext.org/v1/schema/ctx}value"/&gt;
 *         &lt;element ref="{http://nanocontext.org/v1/schema/ctx}list"/&gt;
 *         &lt;element ref="{http://nanocontext.org/v1/schema/ctx}ref"/&gt;
 *         &lt;element ref="{http://nanocontext.org/v1/schema/ctx}properties-ref"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConstructorArgType", propOrder = {
    "bean",
    "value",
    "list",
    "ref",
    "propertiesRef"
})
public class ConstructorArgType {

    protected BeanType bean;
    protected String value;
    protected ListType list;
    protected ReferenceType ref;
    @XmlElement(name = "properties-ref")
    protected PropertiesReferenceType propertiesRef;
    @XmlAttribute(name = "index")
    protected Integer index;

    /**
     * Gets the value of the bean property.
     * 
     * @return
     *     possible object is
     *     {@link BeanType }
     *     
     */
    public BeanType getBean() {
        return bean;
    }

    /**
     * Sets the value of the bean property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeanType }
     *     
     */
    public void setBean(BeanType value) {
        this.bean = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link ListType }
     *     
     */
    public ListType getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListType }
     *     
     */
    public void setList(ListType value) {
        this.list = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setRef(ReferenceType value) {
        this.ref = value;
    }

    /**
     * Gets the value of the propertiesRef property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesReferenceType }
     *     
     */
    public PropertiesReferenceType getPropertiesRef() {
        return propertiesRef;
    }

    /**
     * Sets the value of the propertiesRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesReferenceType }
     *     
     */
    public void setPropertiesRef(PropertiesReferenceType value) {
        this.propertiesRef = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIndex(Integer value) {
        this.index = value;
    }

}
