//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.21 at 10:08:23 AM EDT 
//


package org.nanocontext.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://nanocontext.org/v1/schema/ctx}bean"/&gt;
 *           &lt;element ref="{http://nanocontext.org/v1/schema/ctx}value"/&gt;
 *           &lt;element ref="{http://nanocontext.org/v1/schema/ctx}list"/&gt;
 *           &lt;element ref="{http://nanocontext.org/v1/schema/ctx}ref"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListType", propOrder = {
    "beanOrValueOrList"
})
public class ListType {

    @XmlElements({
        @XmlElement(name = "bean", type = BeanType.class),
        @XmlElement(name = "value", type = String.class),
        @XmlElement(name = "list", type = ListType.class),
        @XmlElement(name = "ref", type = ReferenceType.class)
    })
    protected List<Object> beanOrValueOrList;

    /**
     * Gets the value of the beanOrValueOrList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beanOrValueOrList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeanOrValueOrList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BeanType }
     * {@link String }
     * {@link ListType }
     * {@link ReferenceType }
     * 
     * 
     */
    public List<Object> getBeanOrValueOrList() {
        if (beanOrValueOrList == null) {
            beanOrValueOrList = new ArrayList<Object>();
        }
        return this.beanOrValueOrList;
    }

}
